// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file protobuf_string_sync.proto (package protobuf_string_sync, syntax proto3)
/* eslint-disable */

import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";

export const protobufPackage = "protobuf_string_sync";

/**
 * @generated from message protobuf_string_sync.ExampleMsg
 */
export interface ExampleMsg {
  /**
   * @generated from field: string example_text = 1;
   */
  exampleText?: string;

};

export const ExampleMsg: MessageType<ExampleMsg> = /* @__PURE__ */ createMessageType({
    typeName: "protobuf_string_sync.ExampleMsg",
    fields: [
        { no: 1, name: "example_text", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

